### PR TITLE
BuiltValueFiled adds `string` argument 

### PR DESCRIPTION
**Pull request by TshineZheng**
import Built_Value as xx support
BuiltValueFiled adds `string` argument ( Important )

---
This change is [Reviewable](https://reviewable.io/reviews/google/built_value.dart/619)

### CODE REVIEW

**Comment by TshineZheng** [comment]
I signed it!

**Comment by TshineZheng** [comment]
I hope these two features can have official support

**Comment by davidmorgan** [comment]
Sorry for the slow response.

I don't really understand what this code is doing. Would you mind giving an example of how this will be used, please?

**Comment by TshineZheng** [comment]
# BuiltValueFiled  string 
```dart
abstract class UploadImageState implements Built<UploadImageState, UploadImageStateBuilder> {

  String get assetID;

  @BuiltValueField(string: false)
  CancelToken get uploadCancelToken;

}
```
`toString` will be
```dart
  @override
  String toString() {
    return (newBuiltValueToStringHelper('UploadImageState')
          ..add('assetID', assetID)
         // skip uploadCancelToken
        )
        .toString();
  }
```
# import Built_Value as xx support

```dart
import 'package:built_value/built_value.dart' as BV; 
import 'package:flutter/material.dart';

abstract class SomeState implements BV.Built<SomeState, SomeStateBuilder>{

  @BV.BuiltValueField(compare: false, serialize: false, string: false)
  TextEditingController get introEditController;

  ...
  ...
  ...
}
```
as you know , use `flutter material.dart` and `buitvalue.dart` at same time，`Buildler` will conflict , because The name 'Builder ' is defined in the libraries 'package :built_value/built_value.dart ' and 'package :flutter/src/widgets/basic.dart .

**Comment by davidmorgan** [comment]
Thanks. I think those broadly make sense as features, but they will need some work to land:

 - Please split them into two separate PRs, one for each feature
 - The import prefix support will need to apply everywhere in `built_value`: also for enums and serialization.
 - There will need to be test coverage. You need to run `tool/use_local_deps` before the different packages (e.g. `end_to_end_test`) can run against each other. Then `tool/presubmit` will run all the tests. Please add to `end_to_end_test` to fully cover the new features.

**Comment by TshineZheng** [comment]
@davidmorgan 
ok, thanks for your suggestion,  i will try at sometimes after holiday.

**Pull request closed without merging**
