### PR TITLE
build_value_generator: support latest dependencies

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@davidmorgan – zero clue how your changelog setup works.

Would love to get this out soon!

**Comment by dave26199** [comment]
Sorry, I thought I replied to this a few days ago.

Looking at the travis output--it runs pub upgrade--it looks like it's also needed to bump the analyzer plugin version to allow the analyzer update.

I'm on vacation--is anything blocked on this? Not sure if I have access to publish to pub from here, but I can merge the PR. Will have access on Tue.

**Comment by kevmoo** [comment]
We're no blocked AFAIK – but this may block downstream folks from getting
latest bits.

**Comment by kevmoo** [comment]
ping @dave26199 ?

**Comment by davidmorgan** [comment]
Sorry for the slow response! Now fully back. I'll get this published.

**Pull request merged**
