### PR TITLE
Support generics

### LINKED ISSUE #7: Support value types using generics

### PR DESCRIPTION
**Pull request by davidmorgan**
Fixes #7 

Note that "golden file" tests for the serializer generation are removed. Generated serializer code is tested via the "example" classes, which is less brittle.

This change is [Reviewable](https://reviewable.io/reviews/google/built_value.dart/88)

### CODE REVIEW

**Comment by brianegan** [comment]
Two for two! Any way we, the community, help getting these landed? 

1800 line PRs are a bit tough to review, especially in projects that I don't know well. Any way we can help test, for example?

**Comment by davidmorgan** [comment]
:)

No worries, I'll find someone to review. I'm just back from vacation, as is the person who usually reviews.

**Comment by manuelF** [comment]
:lgtm:

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[built_value_generator/lib/src/serializer_source_class.dart, line 83 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabCjEJmde7QYsTlqOS:-KabCjEKRXJnbrCFCvOi:b-svxnfq) ([raw file](https://github.com/google/built_value.dart/blob/4f31606410eb01c0caa1d843a2b3529479c4b75b/built_value_generator/lib/src/serializer_source_class.dart#L83)):*
> ```Dart
>             field
>                 .generateFullType(genericParameters.toBuiltSet())
>                 .startsWith('const '))
> ```

Why this is 'const' required?

---

*[built_value_generator/lib/src/serializer_source_class.dart, line 193 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabJbcraY6yiVbVvOqL:-KabJbcraY6yiVbVvOqM:b-4pfeff) ([raw file](https://github.com/google/built_value.dart/blob/4f31606410eb01c0caa1d843a2b3529479c4b75b/built_value_generator/lib/src/serializer_source_class.dart#L193)):*
> ```Dart
>     for (final parameter in parameters) {
>       final index = genericParameters.indexOf(parameter);
>       result.writeln('final p$parameter = isUnderspecified ? FullType.object : '
> ```

this produces code like
final pT = isUnderspecified...

which is hard to understand to realize that pT refers to parameter <T>.
Can you do something like parameter_T? I know it is not camelCase style but it is much more obvious that this is generated and what it refers to

---

*[built_value_generator/lib/src/value_source_class.dart, line 420 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabEhL3AXaZu1Hv5fSq:-KabEhL4CrMaeXULWxK2:bcs4qgu) ([raw file](https://github.com/google/built_value.dart/blob/4f31606410eb01c0caa1d843a2b3529479c4b75b/built_value_generator/lib/src/value_source_class.dart#L420)):*
> ```Dart
>         result.writeln(
>             'if ($genericParameter == dynamic) throw new ArgumentError.value('
>             "'dynamic', '$genericParameter');");
> ```

add some extra bit here to say this is an unexpected state, and all args should be defined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/88#-:-KabNQqxyYOQw8TVcasW:bnfp4nl)*

**Comment by davidmorgan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[built_value_generator/lib/src/serializer_source_class.dart, line 83 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabCjEJmde7QYsTlqOS:-Kabn31v94bB23P33otX:bl152hq) ([raw file](https://github.com/google/built_value.dart/blob/47719328227fc8f4eaaf7141e30d1aed1e46d7d5/built_value_generator/lib/src/serializer_source_class.dart#L83)):*
<details><summary><i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary><blockquote>

Why this is 'const' required?
</blockquote></details>

generateFullType returns code that starts with const iff the type is fully known at runtime -- which means we can add a builder factory for it.

Using const when the type is fully known at runtime is an optimization -- otherwise we'd e.g. allocate a new FullType(BuiltList, [new FullType(String)]) for every BuiltList<String> in the app. This way, we only allocate one -- faster to check for equality, and uses less memory.

---

*[built_value_generator/lib/src/serializer_source_class.dart, line 193 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabJbcraY6yiVbVvOqL:-KabnSGySslbp52O-NQt:b-4n9w54) ([raw file](https://github.com/google/built_value.dart/blob/47719328227fc8f4eaaf7141e30d1aed1e46d7d5/built_value_generator/lib/src/serializer_source_class.dart#L193)):*
<details><summary><i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary><blockquote>

this produces code like
final pT = isUnderspecified...

which is hard to understand to realize that pT refers to parameter <T>.
Can you do something like parameter_T? I know it is not camelCase style but it is much more obvious that this is generated and what it refers to
</blockquote></details>

There is currently an issue that it's hard to turn off lints for generated code, so we have to make it pass lints :/ requiring camel case.

But I can make it parameterT, that's definitely clearer. Done.

---

*[built_value_generator/lib/src/value_source_class.dart, line 420 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabEhL3AXaZu1Hv5fSq:-Kabo6YmfigWTjDNpbXm:bk2xoaq) ([raw file](https://github.com/google/built_value.dart/blob/47719328227fc8f4eaaf7141e30d1aed1e46d7d5/built_value_generator/lib/src/value_source_class.dart#L420)):*
<details><summary><i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary><blockquote>

add some extra bit here to say this is an unexpected state, and all args should be defined
</blockquote></details>

Done: "All type arguments must be specified."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/88)*

**Comment by davidmorgan** [comment]
Review status: 24 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

*[built_value_generator/lib/src/serializer_source_class.dart, line 83 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabCjEJmde7QYsTlqOS:-Kabs2729QBrKQSJ4NuI:b-896fix) ([raw file](https://github.com/google/built_value.dart/blob/47719328227fc8f4eaaf7141e30d1aed1e46d7d5/built_value_generator/lib/src/serializer_source_class.dart#L83)):*
<details><summary><i>Previously, davidmorgan (David Morgan) wrote…</i></summary><blockquote>

generateFullType returns code that starts with const iff the type is fully known at runtime -- which means we can add a builder factory for it.

Using const when the type is fully known at runtime is an optimization -- otherwise we'd e.g. allocate a new FullType(BuiltList, [new FullType(String)]) for every BuiltList<String> in the app. This way, we only allocate one -- faster to check for equality, and uses less memory.
</blockquote></details>

Done.

---

*[built_value_generator/lib/src/serializer_source_class.dart, line 193 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabJbcraY6yiVbVvOqL:-Kabs3BDLWqfzuTvqo99:b-896fix) ([raw file](https://github.com/google/built_value.dart/blob/47719328227fc8f4eaaf7141e30d1aed1e46d7d5/built_value_generator/lib/src/serializer_source_class.dart#L193)):*
<details><summary><i>Previously, davidmorgan (David Morgan) wrote…</i></summary><blockquote>

There is currently an issue that it's hard to turn off lints for generated code, so we have to make it pass lints :/ requiring camel case.

But I can make it parameterT, that's definitely clearer. Done.
</blockquote></details>

Done.

---

*[built_value_generator/lib/src/value_source_class.dart, line 420 at r1](https://reviewable.io:443/reviews/google/built_value.dart/88#-KabEhL3AXaZu1Hv5fSq:-Kabs3hkjBQMA5ZmXS5H:b-896fix) ([raw file](https://github.com/google/built_value.dart/blob/47719328227fc8f4eaaf7141e30d1aed1e46d7d5/built_value_generator/lib/src/value_source_class.dart#L420)):*
<details><summary><i>Previously, davidmorgan (David Morgan) wrote…</i></summary><blockquote>

Done: "All type arguments must be specified."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/88)*

**Pull request merged**
