### PR TITLE
Update for built_value_generator

### PR DESCRIPTION
**Pull request by JEuler**
Needed this for compatibility with a maintained library (https://github.com/lejard-h/chopper)
Tests for generator are passing

### CODE REVIEW

**Comment by JEuler** [comment]
@googlebot I signed it!

**Comment by diegotori** [comment]
@davidmorgan is there any chance that you can please review this, since this is preventing chopper from adopting null-safety? Thanks in advance.

**Comment by davidmorgan** [comment]
I looked into this today but hit problems with test timeouts--need to figure out if they are related to the version bumps or a local issue. Will try again tomorrow.

Sorry for the delay.

**Comment by JEuler** [comment]
Okay, if I can help with anything, ping me. Tests are passing locally for me, for built_generator_test :)

**Comment by davidmorgan** [comment]
Merged as #1031

**Pull request closed without merging**
