### PR TITLE
Update dependencies of built_value_generator

### PR DESCRIPTION
**Pull request by xavierhainaux**
In order to work with `angular2` 3.1.0

---
This change is [Reviewable](https://reviewable.io/reviews/google/built_value.dart/166)

### CODE REVIEW

**Comment by davidmorgan** [comment]
Thanks. Please also update the other yaml files in the repo -- the presubmit (tool/presubmit) should pass.

**Comment by davidmorgan** [comment]
Thanks! I'll push this to pub now.

**Comment by xavierhainaux** [comment]
Great. Thanks :-)

**Comment by davidmorgan** [comment]
Published as 1.1.1

Thanks!

**Pull request merged**
