### PR TITLE
Added nestedBuilder and autoCreateNestedBuilder per field through @BuiltValueField annotation.

### PR DESCRIPTION
**Pull request by fromlabs**
Feature request #918.

### CODE REVIEW

**Comment by fromlabs** [comment]
Hi @davidmorgan, sorry but I broke this PR merging yesterday from master. Before trying to fix, I'm waiting your feedback because I don't think it's related to my commits.

**Comment by davidmorgan** [comment]
Hi Roberto,

Sorry for the slow response on this! I think I can get to it next week. Thanks for your patience.

**Comment by fromlabs** [comment]
ok, it's fine for me, thank you!

**Comment by davidmorgan** [comment]
Looks good, thanks!

Sorry this took so long.

**Pull request merged**
