### PR TITLE
Fix generation when there are nested multi-parameter generics.

### LINKED ISSUE #125: Support nested generics
Generic support currently only works for one level of nesting, i.e. Foo<Bar> not Foo<Bar<Baz>>. Fix it.

### PR DESCRIPTION
**Pull request by davidmorgan**
Fixes #125

---
This change is [Reviewable](https://reviewable.io/reviews/google/built_value.dart/137)

### CODE REVIEW

**Comment by manuelF** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[end_to_end_test/test/generics_serializer_test.dart, line 349 at r1](https://reviewable.io:443/reviews/google/built_value.dart/137#-KeJLG_R7S_avvrHSDz5:-KeJLG_R7S_avvrHSDz6:b-smpbl4) ([raw file](https://github.com/google/built_value.dart/blob/2f077445401a19149bc094c8a8d8673508b5d1e7/end_to_end_test/test/generics_serializer_test.dart#L349)):*
> .addBuilderFactory(
>           const FullType(BuiltList, const [
>             const FullType(BuiltList, const [const FullType(String)])
>           ]),

Commented code?  What does this mean here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/137)*

**Comment by davidmorgan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[end_to_end_test/test/generics_serializer_test.dart, line 349 at r1](https://reviewable.io:443/reviews/google/built_value.dart/137#-KeJLG_R7S_avvrHSDz5:-KeJM0cWqRBemmfGIQn_:b-v36qgb) ([raw file](https://github.com/google/built_value.dart/blob/2f077445401a19149bc094c8a8d8673508b5d1e7/end_to_end_test/test/generics_serializer_test.dart#L349)):*
<details><summary><i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary><blockquote>

> .addBuilderFactory(
>           const FullType(BuiltList, const [
>             const FullType(BuiltList, const [const FullType(String)])
>           ]),

Commented code?  What does this mean here?
</blockquote></details>

Whoops. Removed!

(Adding these by hand is awkward; as the TODO notes, it should be done automatically.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/137)*

**Comment by manuelF** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/137)*

**Comment by manuelF** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/137#-:-KeJP21oG-P1bh-rcdOZ:bnfp4nl)*

**Pull request merged**
