### PR TITLE
Fix unescaped string usage while generating `ValueSourceClass`

### PR DESCRIPTION
**Pull request by daohoangson**

### CODE REVIEW

**Comment by daohoangson** [comment]
This should fix #784.

**Comment by davidmorgan** [comment]
Thanks. I'd like to make sure this works end to end including serialization; would you mind adding a test to the end_to_end_test package please? That means adding such a field to a value in `end_to_end_test/lib/values.dart` and updating the corresponding serialization test . The presubmit script `tool/presubmit` will check that everything builds okay with no analyzer errors.

Or, I can take a look if you like :)

Fair warning, it usually takes me ~weeks to get around to releasing `built_value` unless there is something urgent.

**Comment by daohoangson** [comment]
> Thanks. I'd like to make sure this works end to end including serialization; would you mind adding a test to the end_to_end_test package please? That means adding such a field to a value in end_to_end_test/lib/values.dart and updating the corresponding serialization test . The presubmit script tool/presubmit will check that everything builds okay with no analyzer errors.

I will attempt to do this myself. Thanks for the pointer.

> Fair warning, it usually takes me ~weeks to get around to releasing built_value unless there is something urgent.

That is understood. Thank you.

**Comment by daohoangson** [comment]
I have updated the PR with tests. Please take another look when you find the time, thank you @davidmorgan.

**Comment by davidmorgan** [comment]
Looks good, thanks! Could you please add a note to `CHANGELOG.md`? Don't worry too much about the details, I'll fix if needed when I next edit the file. Also feel free to add yourself to AUTHORS if you like.

**Comment by daohoangson** [comment]
I have pushed a new commit to address your comment. Thanks @davidmorgan 👍

**Comment by davidmorgan** [comment]
Looks good, thanks!

**Pull request merged**
