### PR TITLE
Fix `Null check operator used on a null value`

### LINKED ISSUE #1013: Null check operator used on a null value when using serializers.serializeWith(serializer, object)
https://github.com/google/built_value.dart/blob/c161995103bb134b21ffe4ab6ecfd71a85d390ad/built_value/lib/src/built_json_serializers.dart#L67

## Log
```
Null check operator used on a null value, #0      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:67:51)
#1      BuiltListSerializer.serialize.<anonymous closure> (package:built_value/src/built_list_serializer.dart:28:36)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:50:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#8      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:103:14)
#9      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:69:18)
#10     _$MemberRes<…>
```

### PR DESCRIPTION
**Pull request by hoc081098**
Fixes #1013

### CODE REVIEW

**Comment by davidmorgan** [comment]
Sorry I've been so slow getting to this--will try to take a look soon.

I'd like to be sure we get this right :)

One tip: please run tool/use_local_deps so that built_value_generator and end_to_end_test use this updated version; then it's possible to check with end to end tests that this works as expected.

**Comment by davidmorgan** [comment]
Sorry for the continued slow response on this--I think I will get to it next week.

**Comment by hoc081098** [comment]
> Sorry for the continued slow response on this--I think I will get to it next week.

Thanks

**Comment by JacobT14** [comment]
@davidmorgan any eta on this?  This is currently blocking us.  We have a third-party dependency that generates code for us from our graphql schema, and produces a class with a field of List<String> for example.  When we get a json response of [null, "1", "2", "3"] the app crashes due to this null check operator error.  As of right now we aren't able to migrate 100% to null safety(and the dependency would have to migrate as well), so this fix would unblock us.

**Comment by davidmorgan** [comment]
I will be making various changes along these lines with the next release, PRs currently being sent/reviewed. Thanks for the original PR and sorry this took so long!

**Pull request closed without merging**
