### PR TITLE
feat: allow non alphanumeric characters in enum class names

### PR DESCRIPTION
**Pull request by Leptopoda**
fixes: #1292

### CODE REVIEW

**Comment by davidmorgan** [comment]
Looks good, thanks!

**Comment by davidmorgan** [comment]
I'll aim to release next week.

**Comment by Leptopoda** [comment]
Hi david, any news on when we can expect the next release?
No pressure but it would be great being able to plan on our side.

**Comment by davidmorgan** [comment]
Done! Thanks for your patience :)

And thanks for the improvement and fix, much appreciated :)

**Pull request merged**
