### PR TITLE
Improve error output on failure to generate.

### PR DESCRIPTION
**Pull request by davidmorgan**
This change is [Reviewable](https://reviewable.io/reviews/google/built_value.dart/28)

### CODE REVIEW

**Comment by manuelF** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[built_value_generator/lib/built_value_generator.dart, line 186 \[r1\]](https://reviewable.io:443/reviews/google/built_value.dart/28#-KKdcq4fzdnEUB7TO8xX:-KKdcq4fzdnEUB7TO8xY:-363378806) ([raw file](https://github.com/google/built_value.dart/blob/5bc6eff8c79d212f0dd20e0860da0179f844f5a9/built_value_generator/lib/built_value_generator.dart#L186)):*
> ```Dart
>       result.add('Make builder have exactly these fields: ' +
>           fieldNames.join(', ') +
>           '.');
> ```

Wouldn't the period make it harder to copy-paste? At least put a space before it so it is simpler. Or write them as lists so it is more evident that they are tokens and not text, e.g: 

X. Make builder have exactly these fields: [foo, bar, baz, buz].

---

*[built_value_generator/lib/built_value_generator.dart, line 333 \[r1\]](https://reviewable.io:443/reviews/google/built_value.dart/28#-KKdeZdtGL5ZN4db3uog:-KKdeZdu6_ya_71czysV:2021556784) ([raw file](https://github.com/google/built_value.dart/blob/5bc6eff8c79d212f0dd20e0860da0179f844f5a9/built_value_generator/lib/built_value_generator.dart#L333)):*
> ```Dart
>     final message = new StringBuffer(
>         'Please make the following changes to use built_value:\n');
>     for (var i = 0; i != todos.length; ++i) {
> ```

i < todos.length is more idiomatic, I believe.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/28)*

**Comment by davidmorgan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[built_value_generator/lib/built_value_generator.dart, line 186 \[r1\]](https://reviewable.io:443/reviews/google/built_value.dart/28#-KKdcq4fzdnEUB7TO8xX:-KKe0gFr6bVpn40ZgLKp:809535608) ([raw file](https://github.com/google/built_value.dart/blob/5bc6eff8c79d212f0dd20e0860da0179f844f5a9/built_value_generator/lib/built_value_generator.dart#L186)):*
<details><summary><i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary>
> Wouldn't the period make it harder to copy-paste? At least put a space before it so it is simpler. Or write them as lists so it is more evident that they are tokens and not text, e.g: 
> 
> X. Make builder have exactly these fields: [foo, bar, baz, buz].
</details>
Good point, the ones that are code should not have a period. Will revert.

---

*[built_value_generator/lib/built_value_generator.dart, line 333 \[r1\]](https://reviewable.io:443/reviews/google/built_value.dart/28#-KKdeZdtGL5ZN4db3uog:-KKe0l3I5e9Tx9uMjvVK:-409787730) ([raw file](https://github.com/google/built_value.dart/blob/5bc6eff8c79d212f0dd20e0860da0179f844f5a9/built_value_generator/lib/built_value_generator.dart#L333)):*
<details><summary><i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary>
> i < todos.length is more idiomatic, I believe.
</details>
I always write for loops like this :)

It means the loop has a stronger postcondition: it will terminate when i is exactly todos.length, and not when it's todos.length+1, +2, +100...

If you happen to be proving something about what the loop will do, this is much better.

But the reason I like it in practice is that it makes clear that I know i is not going to start bigger than todos.length. Occasionally you don't know whether the loop will execute at all, and if you get into the habit of using !=, you'll have to handle these cases differently. (Which you probably should anyway).

I can change it if you like. Up to you :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/28)*

**Comment by manuelF** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[built_value_generator/lib/built_value_generator.dart, line 333 \[r1\]](https://reviewable.io:443/reviews/google/built_value.dart/28#-KKdeZdtGL5ZN4db3uog:-KKe2pn6DHQa_GBaZQ5e:886869941) ([raw file](https://github.com/google/built_value.dart/blob/5bc6eff8c79d212f0dd20e0860da0179f844f5a9/built_value_generator/lib/built_value_generator.dart#L333)):*
<details><summary><i>Previously, davidmorgan (David Morgan) wrote…</i></summary>
> I always write for loops like this :)
> 
> It means the loop has a stronger postcondition: it will terminate when i is exactly todos.length, and not when it's todos.length+1, +2, +100...
> 
> If you happen to be proving something about what the loop will do, this is much better.
> 
> But the reason I like it in practice is that it makes clear that I know i is not going to start bigger than todos.length. Occasionally you don't know whether the loop will execute at all, and if you get into the habit of using !=, you'll have to handle these cases differently. (Which you probably should anyway).
> 
> I can change it if you like. Up to you :)
</details>
Your reasoning is solid, agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/28)*

**Comment by manuelF** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_value.dart/28#-:-KKe341eiotoe9pVAFPj:1417088721)*

**Pull request merged**
