### PR TITLE
feat: re-added support for serializeNulls

### LINKED ISSUE #604: null values are stripped when serializing
Hello, thanks for a wonderful plugin. It's making our boilerplate related headacres go away.

However we're running into a minor issue serializing data into a Firestore compatible Map. The generated serializers are stripping out nulls (which makes sense in a JSON context).

The offending code is the `if` that is generated in the `.g.dart` files, for example:
```
if (object.color != null) {
      result
        ..add('color')
        ..add(serializers.serialize(object.color,
            specifiedType: const FullType(String)));
}
```

If we comment it out, our resulting Map has keys with nulls, as desired.

Any way to make built_value not generate that `if` check?

### PR DESCRIPTION
**Pull request by larssn**
This basically uses most of the old code, with a few exceptions.

I have no idea how to test this code without modifying the .pub-cache, since most of the packages references external dependencies. So it probably shouldn't be merged before someone explains how to do that.

Closes #604

### CODE REVIEW

**Comment by dave26199** [comment]
Try tool/set_local_version then tool/presubmit ... sorry for brief reply,
posting from phone ... will try to take a look this week.

**Comment by larssn** [comment]
Thanks for the tip!

It works, however it's close to how it was before. Might need a more thorough solution for NNBD.

**Comment by larssn** [comment]
Don't merge, there seems to be a problem serializing lists that can be null.

**Comment by larssn** [comment]
Added end to end tests for `null` lists and maps (which fail).

Doesn't seem trivial to fix those two. And I fear the only workaround for now is not use `serializeNulls: true` and lists/maps together.

**Comment by larssn** [comment]
Testing the code in our app reveals even more problems. Gonna close this as its not viable.

**Comment by larssn** [comment]
@davidmorgan We've been testing this PR together with #1015, and we've not had any problems.

**Pull request closed without merging**
