### PR TITLE
Supply new pathContext parameter to ContextRoot

### PR DESCRIPTION
**Pull request by stereotype441**
@davidmorgan

---
This change is [Reviewable](https://reviewable.io/reviews/google/built_value.dart/431)

### CODE REVIEW

**Comment by davidmorgan** [comment]
Hmm, travis says there are issues with version resolution, could you take a look please?

https://travis-ci.org/google/built_value.dart/builds/385762890?utm_source=github_status&utm_medium=notification

Thanks.

**Comment by stereotype441** [comment]
Looks like I need to publish a new version of analyzer_plugin that's compatible with analyzer version 0.32.1.  I'll do that and get back to you.

**Comment by stereotype441** [comment]
@davidmorgan Ok, I've published a new version of analyzer_plugin so I believe the Travis CI build should pass now.  I don't know how to re-trigger it, though.

**Comment by davidmorgan** [comment]
@stereotype441 still looks red:

Resolving dependencies... 
Because analyzer_plugin <0.0.1-alpha.2 depends on analyzer ^0.31.0-alpha.1 and built_value_generator depends on analyzer ^0.32.1, analyzer_plugin <0.0.1-alpha.2 is forbidden.
So, because built_value_generator depends on analyzer_plugin 0.0.1-alpha.0, version solving failed.

Looks like the analyzer_plugin dependency needs changing too?

**Comment by stereotype441** [comment]
@davidmorgan Sorry about that!  The Travis checks pass now.

**Comment by davidmorgan** [comment]
Thanks. Do you need me to publish to pub+pull into google3?

**Comment by stereotype441** [comment]
That would be great, thank you!

**Pull request merged**
